#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server.

# This is a function that will get executed when the (argc)
# is less than 4.
usage() {
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
}

# Check if number of arguments is less than 4.
# if it is it will call the usage function.
if [ "$#" -lt 4 ]; then
    usage
fi

# Assigning the arguments to variables.
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Transfer the file using scp to the server's home directory.
# with the strict host key checking disabled.
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$SERVER_IP":~/
