#!/usr/bin/env bash
# A script that displays the content of the current directory
# in a list format where only the part of the name
# after the first dash is displayed (refer to the example)

list=$(ls)

for i in $list
do
    echo "$i" | cut -d '-' -f2
done
