#!/usr/bin/env bash
# A Bash script that creates an RSA key pair.
# Name must be school, number of bits 4096 &
# must be protected by passphrase "betty".
ssh-keygen -b 4096 -f school -N betty

# -b 4096: Specify the number of bit in the key
# -n "betty": Specify the passphrase to use for
            # encrypting the private key
# -f school: Specify the filename of the key file
