#!/usr/bin/env bash
# SSH client configuration
# This configuration specifies settings for connecting to the server with IP address 3.85.148.212.
# IdentityFile specifies the private key to use for authentication.
# In this case, it points to the private key located at ~/.ssh/school.
# PreferredAuthentications specifies the preferred order of authentication methods.
# Here, it's set to "publickey" to prioritize public key authentication.
# PasswordAuthentication specifies whether password authentication should be allowed.
# Setting it to "no" disables password authentication, ensuring only public key authentication is used.

Host 3.85.148.212
IdentityFile ~/.ssh/school
PreferredAuthentications publickey
PasswordAuthentication no
